### ISSUE TITLE
fling velocity

### ISSUE THREAD

**Issue by the-aditya** [ph0en1x290331/PLAMCamera#1]
Nice work with the filter. Finally found something on filters. Everything went well except i want the fling to be smoother like in snapchat and instagram. Right now its like BAMM! flinged. How can i get that effect life instagram and snapchat.

**Comment by ArunMehra29** [comment]
Sure. Give me some time. I will try to implement it as soon as possible.

**Comment by the-aditya** [comment]
A big Thanks man for a quick reply.. looking forward to it.

**Comment by the-aditya** [comment]
hey man...any progress?

**Comment by ArunMehra29** [comment]
I apologize for the late reply, I've have been busy.

**Comment by ArunMehra29** [comment]
I'll give you a rough sketch of how you can do it. From there you can modify accordingly. Hope that would be helpful.

**Comment by the-aditya** [comment]
sure.. that wud be helpful.

**Comment by ArunMehra29** [comment]
Hi, I've updated the code in the branch 'feature/fling-velocity-changed'. It is a very rough solution to the requirement. You can refine it according to your need.
